version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - llama
    environment:
      - POSTGRES_USER=bookuser
      - POSTGRES_PASSWORD=bookpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=bookdb
      - SECRET_KEY=yoursecretkey
      - LLAMA_MODEL_HOST=llama
      - LLAMA_MODEL_PORT=8080
    volumes:
      - ./:/app
    restart: always

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      -
